-- 1. Tạo Login cho dịch vụ SSAS vào Server
USE [master]
GO
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'NT SERVICE\MSOLAP$SSAS_MULTI')
BEGIN
    CREATE LOGIN [NT SERVICE\MSOLAP$SSAS_MULTI] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
END
GO

-- 2. Cấp quyền đọc dữ liệu trong Database AirlineDWH
USE [AirlineDWH]
GO
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NT SERVICE\MSOLAP$SSAS_MULTI')
BEGIN
    CREATE USER [NT SERVICE\MSOLAP$SSAS_MULTI] FOR LOGIN [NT SERVICE\MSOLAP$SSAS_MULTI]
END
GO
ALTER ROLE [db_datareader] ADD MEMBER [NT SERVICE\MSOLAP$SSAS_MULTI]
GO
